### ISSUE TITLE
Unauthenticated new student doesn't route back to their spot in the booking flow

### ISSUE THREAD

**Issue by Johnsalzarulo** [jeanpaulsio/whiztutor-mobile#30]
When a new student usages the app for the first time, goes through the search flow, creates account it starts over the search flow. Ideally this routes back to the tutor profile or at least the tutor search results. 
Video: https://www.youtube.com/watch?v=YpY2mM1gOr0

**Comment by jeanpaulsio** [comment]
Was the user just created? it should redirect to a user's current spot in the booking flow ONLY if `new_user` is sent back as true

I tested on my end on very new user and it should redirect back to their profile

The reason i have to check for new_user and not just send all students to an arbitrary spot in "booking_flow" is that things seem to break otherwise. 

a big part of this has to do with the stack navigation thing that doesn't "pop" screens off the stack automatically. so for a user that returns true for `new_user`, this is ok - but potentially breaks crap if they are existing

**Comment by jeanpaulsio** [comment]
v3 token controller still had a question mark on "new_user?" on master branch. just submitted a PR so this should fix it

**Comment by Johnsalzarulo** [comment]
💯 sorry about that thanks
