### ISSUE TITLE
New Booking Confirmation Screen 

### ISSUE THREAD

**Issue by Johnsalzarulo** [jeanpaulsio/whiztutor-mobile#33]
This screen needs a little refactoring: 
- [ ] **As a student I have no idea that my session isn’t final, that it’s waiting to be confirmed.** 
     - Ryan Says: (GO with this ✅ Ryan approved)
         - He also didn't love the owl. 
         - No check mark - It makes it seem to "final" it's still not confirmed!
         - **For the text let's go with this:**  
         - Request Sent! What's next? Bookings are usually confirmed within 2 -3 Hours, you'll get a notification once it's confirmed. 
to long to confirm try booking a different tutor.
- [ ] The owl seems very negative, he’s staring at me like I did something wrong. 
- [ ] I think we should drop “View My Tutors” and only have one action on this screen, “My Bookings” as the only Call to action. 
- Don’t care much about the aesthetics I do think it’s important to communicate the state of the booking as pending clearly. 

<img width="651" alt="screen shot 2017-07-17 at 4 03 25 pm" src="https://user-images.githubusercontent.com/3476109/28293545-7d07e1b4-6b09-11e7-94fe-2e4708651710.png">

**Comment by jeanpaulsio** [comment]
I agree, current wording is weak. "pending" needs to be emphasized more

This screen actually serves a bigger purpose. And sort of ties into the "consistent navigation" problem

The booking flow is as follows 

Search location > set category > select tutor > choose time > confirm booking  > booking success

This applies to booking from "my tutors" as well

**View tutors** > select tutor > choose time > confirm booking > **booking success** 

In order for the user to go through this process, the screens stack on top of each other. So for me to go back to the "main" route i have to send a key from each screen and pass it down to the next 

So if i want to go back from "booking success" > "view tutors", i have to goBack(key from select tutor)

Otherwise, if i route directly: booking success > view tutors  - the stack doesnt reset

The point i'm making is that the "View my tutors" button needs to exist or else a user is stuck on this screen every time they navigate to "My Tutors" - there has to be a way for them to go back to the main screen and not forward to

**Comment by Johnsalzarulo** [comment]
Oh! Cool, the double navigation makes sense then, ignore that feedback.

**Comment by jeanpaulsio** [comment]
really like the full screen message. finally figured out how to overlay on top of the header and tab navigation

**Comment by jeanpaulsio** [comment]
![img_3062](https://user-images.githubusercontent.com/8096483/28304684-9fcb7ff0-6b4d-11e7-8920-4c35a854d846.PNG)

the arrow routes to the main index of "my tutors"

which is the opposite of what you said about going to "my bookings" but i can't get it to work right now

going to close for now

**Comment by jeanpaulsio** [comment]
i think it has to do with this screen being a "modal"

the reason i'm using a "modal" is because its the easiest way to achieve that full screen effect on top of the navigation bar at the top and the tab bar at the bottom

my guess is that the routing from the modal can only "dismiss" or go back but can't jump ahead forward? i don't know, that doesn't sound right but i'm willing to live with this. though i would rather have it just jump to bookings as well

**Comment by jeanpaulsio** [comment]
Another option could be just doing a full white screen with mint text, show both buttons for "view my tutors" and "view my bookings"  while showing the top and bottom navigation bars

**Comment by Johnsalzarulo** [comment]
The full screen confirmations are so nice. I really love this. I think the navigation to "My Tutors" is fine. Although I'm with you that we might want to tweak in the future....
